### ISSUE TITLE
Profile information

### ISSUE THREAD

**Issue by wpsimon09** [HangoutSafari/Hangout-Safari#35]
![image](https://github.com/HangoutSafari/Hangout-Safari/assets/95319163/61886e7c-21b2-4522-ba68-14dccde9ebd3)

# Mobile

![image](https://github.com/HangoutSafari/Hangout-Safari/assets/95319163/0a0b62f3-ff75-4586-8367-26aa62ebe27b)

**Comment by TonevS** [comment]
**ESTIMATED** - 1 hour
**REALIZED** - 1 hour 30 minutes
