### ISSUE TITLE
Component for User Image

### ISSUE THREAD

**Issue by JulienNout** [HangoutSafari/Hangout-Safari#36]
Component that shows image of the user next to its name.

**Comment by JulienNout** [comment]
<img width="587" alt="Screenshot 2023-11-20 at 11 26 12" src="https://github.com/HangoutSafari/Hangout-Safari/assets/90240198/7cecdde7-e190-41f9-8c84-299999a75911">

**Comment by TonevS** [comment]
**ESTIMATED** - 20 minutes
**REALIZED** - 2o minutes
