### ISSUE TITLE
Component for  top-navbar

### ISSUE THREAD

**Issue by Simon-Manasse** [HangoutSafari/Hangout-Safari#39]
This will contain the logo component and the navbar buttons component

**Comment by JulienNout** [comment]
<img width="590" alt="Screenshot 2023-11-20 at 11 21 25" src="https://github.com/HangoutSafari/Hangout-Safari/assets/90240198/5a1c08e1-aa3d-4e17-9a38-d17f233735ac">

**Comment by JulienNout** [comment]
<img width="150" alt="Screenshot 2023-11-20 at 11 32 03" src="https://github.com/HangoutSafari/Hangout-Safari/assets/90240198/c46c413b-af49-475a-8718-91994cc0962e">

**Comment by Patrik835** [comment]
ESTIMATED 8 hours
REALIZED  12 hours
