### ISSUE TITLE
API responses and calls for each MS

### ISSUE THREAD

**Issue by wpsimon09** [HangoutSafari/Hangout-Safari#5]

**Comment by TonevS** [comment]
Link to Notion [page](https://www.notion.so/d241aae7fd0a48329b682804d9dd9557?v=09e04dadb61744b6bf7c5ecc06ef37e6&p=055e945da7804847ba4de7a7033d595a&pm=c)

**Comment by TonevS** [comment]
**ESTIMATED** - 30 minutes
**REALIZED** - 30 minutes
