### ISSUE TITLE
Finish the design

### ISSUE THREAD

**Issue by wpsimon09** [HangoutSafari/Hangout-Safari#7]

**Comment by TonevS** [comment]
Currently working on in [figma](https://www.figma.com/file/Iq7Jgx2nsxW8LGN6rAALTh/Untitled?type=design&node-id=0-1&mode=design&t=1T92SsBAeVGI6NDL-0)

**Comment by TonevS** [comment]
**ESTIMATED** - 3 hour
**REALIZED** - 3 hour 30 minutes
